// File: dom.js Path: web/js/dom.js

export const elements = {
  app: document.getElementById('app'),
  flashOverlay: document.getElementById('flash-overlay'),
  preInputMode: document.getElementById('pre-input-mode'),
  postInputMode: document.getElementById('post-input-mode'),
  postInputContent: document.getElementById('post-input-content'),
  codeInput: document.getElementById('code-input'),
  startButton: document.getElementById('start-button'),
  inputError: document.getElementById('input-error'),
  progressCount: document.getElementById('progress-count'),
  progressCountPost: document.getElementById('progress-count-post'),
  progressBarInner: document.getElementById('progress-bar-inner'),
  progressBarInnerPost: document.getElementById('progress-bar-inner-post'),

  hibiscusLogoTopBtn: document.getElementById('hibiscus-logo-top-btn'),
  divisionBadge: document.getElementById('division-badge'),
  divisionLogo: document.getElementById('division-logo'),
  panitiaPhoto: document.getElementById('panitia-photo'),
  panitiaNama: document.getElementById('panitia-nama'),
  panitiaDivisi: document.getElementById('panitia-divisi'),
  panitiaMessage: document.getElementById('panitia-message'),
  dangerLabel: document.getElementById('danger-label'),
  claimButton: document.getElementById('claim-button'),
  backButton: document.getElementById('back-button'),
  selfDestructButton: document.getElementById('self-destruct-button'),
  refreshPrompt: document.getElementById('refresh-prompt'),

  modalEE1Secret: document.getElementById('modal-ee1-secret'),
  modalEE1Notyou: document.getElementById('modal-ee1-notyou'),
  modalEE1Question: document.getElementById('modal-ee1-question'),
  modalOmbInfo: document.getElementById('modal-omb-info'),
  hibiscusLogoBtn: document.getElementById('hibiscus-logo-btn'),
  modalDivisionInfo: document.getElementById('modal-division-info'),
  divisionInfoTitle: document.getElementById('modal-division-info-title'),
  divisionInfoText: document.getElementById('modal-division-info-text'),
  ee1ConfirmBtn: document.getElementById('ee1-question-confirm-btn'),
  ee1Checkboxes: Array.from(document.querySelectorAll('.ee1-checkbox')),
  modalEE2Danger: document.getElementById('modal-ee2-danger'),
  modalEE3Question: document.getElementById('modal-ee3-question'),
  modalEE3Final: document.getElementById('modal-ee3-final'),
  modalEE3Reject: document.getElementById('modal-ee3-reject'),
  modalEE4Bunga: document.getElementById('modal-ee4-bunga'),

  chaosContainer: document.getElementById('chaos-container'),
  modalQuestionText: document.getElementById('modal-question-text'),
  questionYesBtn: document.getElementById('question-yes-btn'),
  questionNoBtn: document.getElementById('question-no-btn'),
  notyouRefreshBtn: document.getElementById('notyou-refresh-btn'),
  notyouFlipBtn: document.getElementById('notyou-flip-btn'),
  dangerRefreshBtn: document.getElementById('danger-refresh-btn'),
  finalRedirectBtn: document.getElementById('final-redirect-btn'),
  rejectRedirectBtn: document.getElementById('reject-redirect-btn'),
  bungaRedirectBtn: document.getElementById('bunga-redirect-btn')
};